"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['surveryGUI.py']
DATA_FILES = ['assets', ('/Users/tristansinclair/Documents/CovidSurveyScript/assets')]
OPTIONS = {
    'iconfile': '/Users/tristansinclair/Documents/CovidSurveyScript/assets/icons.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
